### ISSUE TITLE
Add graph / map showing changes to air quality across different parts of the UK

### ISSUE THREAD

**Issue by HenryFreeman1** [joshuAnalytics/covid_stats#36]
Would be interesting to track changes to air quality from e.g. Jan 2020 onwards in each local borough / council or region, maybe with a sliding timescale to illustrate the changes over time. We can then also use this to track how air quality changes as economic activity starts to pick up again.

Not sure where's best to find this data - will check and come back to this... probs ONS or Met Office?

**Comment by joshuAnalytics** [comment]
think this is a duplicate, closing
